#!/bin/bash
# ProTech Quick Start Guide

echo "═══════════════════════════════════════════════════════════════"
echo "  ProTech - Automated Rent Tracking & Notification System"
echo "  Full-Stack Connection Complete ✅"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📍 LOCATION: ProTech Cur (root folder)"
echo ""
echo "🚀 QUICK START (3 STEPS):"
echo ""
echo "  Step 1: Navigate to the project"
echo "  $ cd /path/to/ProTech\ Cur"
echo ""
echo "  Step 2: Install dependencies (first time only)"
echo "  $ npm run install:all"
echo ""
echo "  Step 3: Start both backend and frontend"
echo "  $ npm run dev"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ SERVICES WILL START ON:"
echo "  • Backend API:  http://localhost:5001"
echo "  • Frontend App: http://localhost:3000"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 CONNECTION CHECKLIST (what was configured):"
echo ""
echo "Backend:"
echo "  ✓ CORS enabled for localhost:3000"
echo "  ✓ Webhook security (raw body parser)"
echo "  ✓ Auth routes: register, login, profile"
echo "  ✓ Payment verification endpoint"
echo "  ✓ Role-based access control"
echo "  ✓ JWT token validation"
echo ""
echo "Frontend:"
echo "  ✓ Axios client with token interceptor"
echo "  ✓ Auth context (persistent login)"
echo "  ✓ Registration form with validation"
echo "  ✓ Login with email/username"
echo "  ✓ Protected routes (role-based)"
echo "  ✓ Payment verification page"
echo "  ✓ Vite dev proxy to backend"
echo ""
echo "Environment:"
echo "  ✓ .env files configured"
echo "  ✓ .gitignore updated (.env excluded)"
echo "  ✓ Root package.json with concurrently"
echo "  ✓ npm scripts for easy startup"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🧪 IMMEDIATE TESTS:"
echo ""
echo "1. Check backend health:"
echo "   curl http://localhost:5001/api/health"
echo ""
echo "2. Open frontend:"
echo "   http://localhost:3000"
echo ""
echo "3. Register a new account:"
echo "   - Click 'Register' tab"
echo "   - Fill in all fields"
echo "   - Choose 'Landlord' role"
echo "   - Submit"
echo ""
echo "4. Sign in with registered account:"
echo "   - Email/Username: (what you registered)"
echo "   - Password: (what you set)"
echo "   - Should redirect to dashboard"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTATION:"
echo "  • INTEGRATION_GUIDE.md    - Full technical details"
echo "  • CONNECTION_STATUS.md    - Complete status report"
echo "  • This file               - Quick reference"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎓 PROJECT:"
echo "  Student: Amoo Halleluyah (241295)"
echo "  School:  SQI College of ICT, Ogbomoso"
echo "  Status:  ✅ COMPLETE - Ready for Testing"
echo ""
echo "═══════════════════════════════════════════════════════════════"
